from django.core.management.base import BaseCommand, CommandError

from colonization_project.models import Person
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from colonization_project.models import Fruits, Vegetable
import json

vegetables = [
    "acorn squash",
    "alfalfa sprout",
    "amaranth",
    "anise",
    "artichoke",
    "arugula",
    "asparagus",
    "aubergine",
    "azuki bean",
    "banana squash",
    "basil",
    "bean sprout",
    "beet",
    "black bean",
    "black-eyed pea",
    "bok choy",
    "borlotti bean",
    "broad beans",
    "broccoflower",
    "broccoli",
    "brussels sprout",
    "butternut squash",
    "cabbage",
    "calabrese",
    "caraway",
    "carrot",
    "cauliflower",
    "cayenne pepper",
    "celeriac",
    "celery",
    "chamomile",
    "chard",
    "chayote",
    "chickpea",
    "chives",
    "cilantro",
    "collard green",
    "corn",
    "corn salad",
    "courgette",
    "cucumber",
    "daikon",
    "delicata",
    "dill",
    "eggplant",
    "endive",
    "fennel",
    "fiddlehead",
    "frisee",
    "garlic",
    "gem squash",
    "ginger",
    "green bean",
    "green pepper",
    "habanero",
    "herbs and spice",
    "horseradish",
    "hubbard squash",
    "jalapeno",
    "jerusalem artichoke",
    "jicama",
    "kale",
    "kidney bean",
    "kohlrabi",
    "lavender",
    "leek ",
    "legume",
    "lemon grass",
    "lentils",
    "lettuce",
    "lima bean",
    "mamey",
    "mangetout",
    "marjoram",
    "mung bean",
    "mushroom",
    "mustard green",
    "navy bean",
    "new zealand spinach",
    "nopale",
    "okra",
    "onion",
    "oregano",
    "paprika",
    "parsley",
    "parsnip",
    "patty pan",
    "pea",
    "pinto bean",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "rhubarb",
    "rosemary",
    "runner bean",
    "rutabaga",
    "sage",
    "scallion",
    "shallot",
    "skirret",
    "snap pea",
    "soy bean",
    "spaghetti squash",
    "spinach",
    "squash",
    "sweet potato",
    "tabasco pepper",
    "taro",
    "tat soi",
    "thyme",
    "topinambur",
    "tubers",
    "turnip",
    "wasabi",
    "water chestnut",
    "watercress",
    "white radish",
    "yam",
    "zucchini",
]

fruits = [
    "açaí",
    "acerola",
    "abiu",
    "ackee",
    "african cucumber",
    "apple",
    "apricot",
    "avocado",
    "banana",
    "bilberry",
    "blackberry",
    "blackcurrant",
    "black sapote",
    "blueberry",
    "boysenberry",
    "breadfruit",
    "buddha's hand (fingered citron)",
    "cactus pear",
    "canistel",
    "cempedak",
    "cherimoya (Custard Apple)",
    "cherry",
    "chico fruit",
    "cloudberry",
    "coco De Mer",
    "coconut",
    "crab apple",
    "cranberry",
    "currant",
    "damson",
    "date",
    "dragonfruit (or Pitaya)",
    "durian",
    "egg Fruit",
    "elderberry",
    "feijoa",
    "fig",
    "finger Lime (or Caviar Lime)",
    "goji berry",
    "gooseberry",
    "grape",
    "raisin",
    "grapefruit",
    "grewia asiatica (phalsa or falsa)",
    "guava",
    "hala Fruit",
    "honeyberry",
    "huckleberry",
    "jabuticaba",
    "jackfruit",
    "jambul",
    "japanese plum",
    "jostaberry",
    "jujube",
    "juniper berry",
    "kaffir Lime",
    "kiwano (horned melon)",
    "kiwifruit",
    "kumquat",
    "lemon",
    "lime",
    "loganberry",
    "longan",
    "loquat",
    "lulo",
    "lychee",
    "magellan Barberry",
    "mamey Apple",
    "mamey Sapote",
    "mango",
    "mangosteen",
    "marionberry",
    "melon",
    "cantaloupe",
    "galia melon",
    "honeydew",
    "mouse melon",
    "musk melon",
    "watermelon",
    "miracle fruit",
    "monstera deliciosa",
    "mulberry",
    "nance",
    "nectarine",
    "orange",
    "blood orange",
    "clementine",
    "mandarine",
    "tangerine",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "persimmon",
    "plantain",
    "plum",
    "prune (dried plum)",
    "pineapple",
    "pineberry",
    "plumcot (or Pluot)",
    "pomegranate",
    "pomelo",
    "purple mangosteen",
    "quince",
    "raspberry",
    "rambutan (or Mamin Chino)",
    "redcurrant",
    "rose apple",
    "salmonberry",
    "salal berry",
    "salak",
    "satsuma",
    "shine Muscat or Vitis Vinifera",
    "sloe or Hawthorn Berry",
    "soursop",
    "surinam cherry",
    "star apple",
    "star fruit",
    "strawberry",
    "tamarillo",
    "tamarind",
    "tangelo",
    "tayberry",
    "tomato",
    "ugli fruit",
    "white currant",
    "white sapote",
    "yuzu",
]


class Command(BaseCommand):
    def handle(self, *args, **options):
        with open("people.json", "r") as person_data:
            persons = json.load(person_data)
            try:
                for person in persons:
                    current_person = Person.objects.get(guid=person.get("guid"))
                    favouriteFood = person.get("favouriteFood")
                    for food in favouriteFood:
                        if food in vegetables:
                            veg, created = Vegetable.objects.get_or_create(name=food)
                            current_person.vegetables.add(veg)
                            continue  # Don't bother checking the next condition

                        if food in fruits:
                            fruit, created = Fruits.objects.get_or_create(name=food)
                            current_person.fruits.add(fruit)

            except Exception as e:
                raise CommandError(e)

        return self.stdout.write(self.style.SUCCESS("Persons' food updated"))
