# Generated by Django 3.2.5 on 2021-07-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonization_project', '0002_alter_person_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fruits', to='colonization_project.person'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='friend',
        ),
        migrations.AddField(
            model_name='person',
            name='friend',
            field=models.ManyToManyField(to='colonization_project.Person'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_veg', to='colonization_project.person'),
        ),
    ]
