# Generated by Django 3.2.5 on 2021-07-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonization_project', '0004_rename_friend_person_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='colonization_project.person'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to='colonization_project.person'),
        ),
    ]
