# Generated by Django 3.2.5 on 2021-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonization_project', '0005_auto_20210727_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='user',
        ),
        migrations.AddField(
            model_name='fruits',
            name='user',
            field=models.ManyToManyField(related_name='fruits', to='colonization_project.Person'),
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='user',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='user',
            field=models.ManyToManyField(related_name='vegetables', to='colonization_project.Person'),
        ),
    ]
